### ISSUE TITLE
`const`ify libgitrev variables

### ISSUE THREAD

**Issue by dmezh** [CooperUnion/selfdrive#86]
https://github.com/CooperUnion/selfdrive/blob/8824006be8980056a8f719f93960c876a9510b4b/dbw/node_fw/lib/libgitrev/libgitrev.h#L7-L8

These are not const and that's an oversight!

**Comment by krunal16-c** [comment]
can i work on this issue and can you please elaborate on the issue.

**Comment by dmezh** [comment]
> can i work on this issue and can you please elaborate on the issue.

Sure. The issue is that those two variables are not const, and they should be, as they don't change after build time. This should be pretty simple; go for it.

**Comment by krunal16-c** [comment]
Hi can you assign me this 
I am not able to push in the dev branch.

**Comment by dmezh** [comment]
@krunal16-c Please fork and open a PR, as we do not allow pushing directly to `dev`.

**Comment by krunal16-c** [comment]
did that !
