### ISSUE TITLE
Report Core Temperature on CAN on Node v1.2

### ISSUE THREAD

**Issue by dmezh** [CooperUnion/selfdrive#99]
ESP32-S3 has a core temperature sensor: https://docs.espressif.com/projects/esp-idf/en/v4.4.2/esp32s3/api-reference/peripherals/temp_sensor.html

Report the temperature on CAN. Please ping me to discuss how to unify the CAN message between 1.1 and 1.2, since 1.1 doesn't have a temp sensor.

**Comment by jacobkoziej** [comment]
Resolved in #130
